### ISSUE TITLE
pasting NEOS inventory link also imports as a hyperlink

### ISSUE THREAD

**Issue by epicEaston197** [rassi0429/NeosPasteTweak#2]
if you copy and paste a inventory link it will also import it as a hyperlink
neosrec:///G-Neos/R-95a40c49-2b4f-46d2-a073-62cc2a8fcba6
![image](https://user-images.githubusercontent.com/76523692/167687999-2e26e186-6e21-42e9-aa22-f2b7ac0e2ed9.png)

**Comment by jonnyawsom3** [comment]
neosdb links might as well get included in this too for the edgecases where it's used
